spring.application.name=jteone

#Application Context path
server.servlet.context-path=/mppkvvcl/ngb/report/jte/backend/api/
server.port=${JTEONE_APP_SERVER_PORT}

#Jte
gg.jte.templateLocation=src/main/jte
gg.jte.templateSuffix=.jte
gg.jte.developmentMode=false
gg.jte.usePrecompiledTemplates=true

#Log
logging.level.org.hibernate=ERROR
logging.level.com.mppkvvcl=DEBUG
logging.level.gg.jte=DEBUG

spring.jackson.time-zone=Asia/Kolkata

#MIS Database details
spring.datasource.mis.url=jdbc:postgresql://${MIS_JTE_DATABASE_SERVER_IP}:${MIS_JTE_DATABASE_SERVER_PORT}/${MIS_JTE_DATABASE_NAME}?currentSchema=${MIS_JTE_DATABASE_SERVER_SCHEMA}
spring.datasource.mis.jdbc-url=jdbc:postgresql://${MIS_JTE_DATABASE_SERVER_IP}:${MIS_JTE_DATABASE_SERVER_PORT}/${MIS_JTE_DATABASE_NAME}?currentSchema=${MIS_JTE_DATABASE_SERVER_SCHEMA}
spring.datasource.mis.username=${MIS_JTE_DATABASE_SERVER_USERNAME}
spring.datasource.mis.password=${MIS_JTE_DATABASE_SERVER_PASSWORD}
spring.datasource.mis.driver-class-name=org.postgresql.Driver
spring.datasource.mis.maximum-pool-size=${MIS_JTE_DATABASE_SERVER_POOLSIZE}
spring.datasource.mis.minimum-idle=0
spring.datasource.mis.idle-timeout=1800000
spring.datasource.mis.max-lifetime=3600000
spring.datasource.mis.pool-name=MISHikariPool

#NGB Database details
spring.datasource.NGB.url=jdbc:postgresql://${NGB_JTE_DATABASE_SERVER_IP}:${NGB_JTE_DATABASE_SERVER_PORT}/${NGB_JTE_DATABASE_NAME}?currentSchema=${NGB_JTE_DATABASE_SERVER_SCHEMA}
spring.datasource.NGB.jdbc-url=jdbc:postgresql://${NGB_JTE_DATABASE_SERVER_IP}:${NGB_JTE_DATABASE_SERVER_PORT}/${NGB_JTE_DATABASE_NAME}?currentSchema=${NGB_JTE_DATABASE_SERVER_SCHEMA}
spring.datasource.NGB.username=${NGB_JTE_DATABASE_SERVER_USERNAME}
spring.datasource.NGB.password=${NGB_JTE_DATABASE_SERVER_PASSWORD}
spring.datasource.NGB.driver-class-name=org.postgresql.Driver
spring.datasource.NGB.maximum-pool-size=${NGB_JTE_DATABASE_SERVER_POOLSIZE}
spring.datasource.NGB.minimum-idle=0
spring.datasource.NGB.idle-timeout=1800000
spring.datasource.NGB.max-lifetime=3600000
spring.datasource.NGB.pool-name=NGBHikariPool

spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.ejb.use_class_enhancer=false
spring.jpa.properties.hibernate.enhancer.enableDirtyTracking=false
spring.jpa.properties.hibernate.enhancer.enableLazyInitialization=false
#spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation= true

#HTML to PDF Conversion
html.pdf.vendor=${HTML_PDF_VENDOR}

#WKHtmlToPdf
html.pdf.converter.api=${HTML_PDF_CONVERTER_API_PATH}